import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({ weight: "400", style: ["normal", "italic"], subsets: ["latin"] });

export const metadata = {
  title: "GreenSaver",
  description: "Generated by GreenSaver app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
